apiVersion: v1
kind: Service
metadata:
  name: pern-backend-service
  namespace: todo-app
spec:
  selector:
    app: pern-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
  type: NodePort

